version: "3.1"
services:
  jackett:
    container_name: jackett
    environment:
      - TZ=Asia/Kolkata
      - AUTO_UPDATE=true
    image: linuxserver/jackett
    ports:
      - "9117:9117"
    volumes:
      - "${BASE_PATH}/config/jackett:/config"
      - blackhole:/downloads

  transmission:
    container_name: transmission
    environment:
      - TZ=Asia/Kolkata
      - "USER=${TRANSMISSION_USER}"
      - "PASS=${TRANSMISSION_PASS}"
    image: linuxserver/transmission
    ports:
      - "9091:9091"
      - "51413:51413"
      - "51413:51413/udp"
    volumes:
      - "${BASE_PATH}/config/transmission:/config"
      - downloads:/downloads
      - blackhole:/watch

  aria2-ui:
    restart: unless-stopped
    image: wahyd4/aria2-ui:latest
    volumes:
      - downloads:/data
    environment:
      - ENABLE_AUTH=false
    ports:
      - "80:80"
  minidlna:
      container_name: minidlna
      network_mode: host
      ports:
          - '8200:8200'
          - '1900:1900/udp'
      volumes:
          - downloads:/opt/Music
          - downloads:/opt/Videos
          - downloads:/opt/Pictures
      image: geekduck/minidlna
volumes:
  blackhole:
    driver: local
    driver_opts:
      device: "${BASE_PATH}/blackhole"
      o: bind
      type: none
  downloads:
    driver: local
    driver_opts:
      device: "${BASE_PATH}/downloads"
      o: bind
      type: none

