version: "3.1"
services:
  jackett:
    container_name: jackett
    environment:
      - TZ=Asia/Kolkata
      - AUTO_UPDATE=true
    image: linuxserver/jackett
    ports:
      - "9117:9117"
    volumes:
      - "${BASE_PATH}/config/jackett:/config"
      - blackhole:/downloads
  sickchill:
    image: linuxserver/sickchill
    container_name: sickchill
    environment:
      - TZ=Asia/Kolkata
    volumes:
      - "${BASE_PATH}/config/sickrage:/config"
      - downloads:/downloads
      - tv:/tv
      - blackhole:/watch
    ports:
      - 8081:8081

  couchpotato:
    image: linuxserver/couchpotato
    container_name: couchpotato
    environment:
      - TZ=Asia/Kolkata
    volumes:
      - "${BASE_PATH}/config/couchpotato:/config"
      - downloads:/downloads
      - movies:/movies
      - blackhole:/watch
    ports:
      - 5050:5050
  transmission:
    container_name: transmission
    environment:
      - TZ=Asia/Kolkata
      - "USER=${TRANSMISSION_USER}"
      - "PASS=${TRANSMISSION_PASS}"
    image: linuxserver/transmission
    ports:
      - "9091:9091"
      - "51413:51413"
      - "51413:51413/udp"
    volumes:
      - "${BASE_PATH}/config/transmission:/config"
      - downloads:/downloads
      - blackhole:/watch
  plex:
    image: linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - VERSION=docker
      - "PLEX_CLAIM=${PLEX_CLAIM}" #optional
    volumes:
      - "${BASE_PATH}/config/plex:/config"
      - tv:/tv
      - movies:/movies
  heimdall:
    image: linuxserver/heimdall
    restart: unless-stopped
    container_name: heimdall
    environment:
      - TZ=Asia/Kolkata
    volumes:
      - "${BASE_PATH}/config/hemidall:/config"
    ports:
      - 8000:80
      - 8443:443
  portainer:
      image: portainer/portainer
      ports:
          - '8001:8000'
          - '9001:9000'
      container_name: portainer
      restart: always
      volumes:
          - '/var/run/docker.sock:/var/run/docker.sock'
          - 'portainer_data:/data'
  aria2-ui:
    restart: unless-stopped
    image: wahyd4/aria2-ui:latest
    volumes:
      - downloads:/data
    environment:
      - ENABLE_AUTH=false
    ports:
      - "8888:80"
volumes:
  portainer_data:
    driver: host
  blackhole:
    driver: local
    driver_opts:
      device: "${BASE_PATH}/blackhole"
      o: bind
      type: none
  downloads:
    driver: local
    driver_opts:
      device: "${BASE_PATH}/downloads"
      o: bind
      type: none
  movies:
    driver: local
    driver_opts:
      device: "${BASE_PATH}/movies"
      o: bind
      type: none
  tv:
    driver: local
    driver_opts:
      device: "${BASE_PATH}/tv_shows"
      o: bind
      type: none
