version: "3.1"
services:
  jackett:
    container_name: jackett
    environment:
      - TZ=Asia/Kolkata
      - AUTO_UPDATE=true
    image: linuxserver/jackett
    ports:
      - "9117:9117"
    volumes:
      - "${BASE_PATH}/config/jackett:/config"
      - blackhole:/downloads
  radarr:
    container_name: radarr
    environment:
      - TZ=Asia/Kolkata
    image: linuxserver/radarr
    ports:
      - "7878:7878"
    volumes:
      - "${BASE_PATH}/config/radarr:/config"
      - movies:/movies
      - downloads:/downloads
      - blackhole:/blackhole
  transmission:
    container_name: transmission
    environment:
      - TZ=Asia/Kolkata
      - "USER=${TRANSMISSION_USER}"
      - "PASS=${TRANSMISSION_PASS}"
    image: linuxserver/transmission
    ports:
      - "9091:9091"
      - "51413:51413"
      - "51413:51413/udp"
    volumes:
      - "${BASE_PATH}/config/transmission:/config"
      - downloads:/downloads
      - blackhole:/watch

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - TZ=Asia/Kolkata
    volumes:
      - ${BASE_PATH}/config/sonarr:/config
      - tv:/tv
      - downloads:/downloads
      - blackhole:/blackhole
    ports:
      - 8989:8989
  plex:
    image: linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - VERSION=docker
      - "PLEX_CLAIM=${PLEX_CLAIM}" #optional
    volumes:
      - "${BASE_PATH}/config/plex:/config"
      - tv:/tv
      - movies:/movies


volumes:
  blackhole:
    driver: local
    driver_opts:
      device: "${BASE_PATH}/blackhole"
      o: bind
      type: none
  downloads:
    driver: local
    driver_opts:
      device: "${BASE_PATH}/downloads"
      o: bind
      type: none
  movies:
    driver: local
    driver_opts:
      device: "${BASE_PATH}/movies"
      o: bind
      type: none
  tv:
    driver: local
    driver_opts:
      device: "${BASE_PATH}/tv_shows"
      o: bind
      type: none
